# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReceiveWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiveWindow(object):
    def setupUi(self, ReceiveWindow):
        ReceiveWindow.setObjectName("ReceiveWindow")
        ReceiveWindow.resize(1000, 900)
        ReceiveWindow.setMinimumSize(QtCore.QSize(1000, 900))
        ReceiveWindow.setMaximumSize(QtCore.QSize(1000, 900))
        self.centralwidget = QtWidgets.QWidget(ReceiveWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(260, 100, 501, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(70, 200, 861, 491))
        self.listWidget.setObjectName("listWidget")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(70, 280, 81, 20))
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 720, 561, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.pushButton1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout2.addWidget(self.pushButton1)
        self.pushButton2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        self.pushButton2.setObjectName("pushButton2")
        self.horizontalLayout2.addWidget(self.pushButton2)
        ReceiveWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ReceiveWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        ReceiveWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ReceiveWindow)
        self.statusbar.setObjectName("statusbar")
        ReceiveWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ReceiveWindow)
        QtCore.QMetaObject.connectSlotsByName(ReceiveWindow)

    def retranslateUi(self, ReceiveWindow):
        _translate = QtCore.QCoreApplication.translate
        ReceiveWindow.setWindowTitle(_translate("ReceiveWindow", "MainWindow"))
        self.label1.setText(_translate("ReceiveWindow", "Return Books"))
        self.pushButton1.setText(_translate("ReceiveWindow", "Return Selected Book"))
        self.pushButton2.setText(_translate("ReceiveWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiveWindow = QtWidgets.QMainWindow()
    ui = Ui_ReceiveWindow()
    ui.setupUi(ReceiveWindow)
    ReceiveWindow.show()
    sys.exit(app.exec_())
